---

- name: install coturn
  become: true
  apt:
    pkg: coturn
    state: present

- name: Give coturn access to TLS cert
  become: true
  user:
    name: turnserver
    groups: "{{ coturn_tls_group }}"
    append: true
  when: coturn_tls and coturn_tls_group is defined

- name: Grant user Turnserver read execute access to /etc/letsencrypt/
  become: true
  acl:
    path: "/etc/letsencrypt/"
    entity: "turnserver"
    etype: "user"
    permissions: "rx"
    recursive: true
    state: present
  when: coturn_tls and not coturn_own_certs

- name: Install custom TLS certificate
  block:
    - name: Ensure target directory exists
      become: true
      file:
        dest: "{{ coturn_tls_cert | dirname }}"
        state: directory
        owner: "turnserver"
        group: "turnserver"
        mode: "0755"

    - name: Deploy custom TLS private key
      become: true
      copy:
        src: '{{ coturn_own_tls_key }}'
        dest: '{{ coturn_tls_key }}'
        owner: "turnserver"
        group: "turnserver"
        mode: '0644'
      notify: restart coturn

    - name: Deploy custom TLS certificate
      become: true
      copy:
        src: "{{ coturn_own_tls_cert }}"
        dest: "{{ coturn_tls_cert }}"
        owner: "turnserver"
        group: "turnserver"
        mode: "0644"
      notify: restart coturn
  when: coturn_tls and coturn_own_certs

- name: Create systemd override for coturn
  block:
    - name: Create needed folder
      become: true
      file:
        path: "/etc/systemd/system/coturn.service.d/"
        state: directory
        mode: "0755"

    - name: Apply coturn override template
      become: true
      template:
        src: override.conf
        dest: "/etc/systemd/system/coturn.service.d/override.conf"
        owner: "root"
        group: "root"
        mode: '0644'
      notify:
        - reload systemd

- name: Create lograte structure
  block:
    - name: Create needed folder
      become: true
      file:
        path: "/var/log/turnserver"
        owner: "turnserver"
        group: "turnserver"
        state: directory
        mode: '0755'

    - name: Template logrotate
      become: true
      template:
        src: "logging.conf"
        dest: "/etc/logrotate.d/coturn"
        owner: "root"
        group: "root"
        mode: "0644"

- name: ensure coturn is enabled
  become: true
  lineinfile:
    dest: "/etc/default/coturn"
    line: "TURNSERVER_ENABLED=1"
    regexp: "^#?TURNSERVER_ENABLED="

- name: Create parameters for Diffie–Hellman (could take a while)
  become: true
  command: "openssl dhparam -out /etc/coturn-dh-{{ coturn_dhparam_length }}.pem {{ coturn_dhparam_length }}"
  args:
    creates: "/etc/coturn-dh-{{ coturn_dhparam_length }}.pem"
  when: coturn_tls
  notify: restart coturn

- name: configure coturn
  become: true
  template:
    dest: "/etc/turnserver.conf"
    src: "turnserver.conf.j2"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: restart coturn
